spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:changelog-master.yaml
app:
  security:
    username: "bat1354"
    password: "Lying Fr0m Y0u"