spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog-master.yaml